(ns rosalind.prot
  (:require
   [clojure.java.io :as io]))

(def rna-codon-table {"UUU" "F"
                      "CUU" "L"
                      "AUU" "I"
                      "GUU" "V"
                      "UUC" "F"
                      "CUC" "L"
                      "AUC" "I"
                      "GUC" "V"
                      "UUA" "L"
                      "CUA" "L"
                      "AUA" "I"
                      "GUA" "V"
                      "UUG" "L"
                      "CUG" "L"
                      "AUG" "M"
                      "GUG" "V"
                      "UCU" "S"
                      "CCU" "P"
                      "ACU" "T"
                      "GCU" "A"
                      "UCC" "S"
                      "CCC" "P"
                      "ACC" "T"
                      "GCC" "A"
                      "UCA" "S"
                      "CCA" "P"
                      "ACA" "T"
                      "GCA" "A"
                      "UCG" "S"
                      "CCG" "P"
                      "ACG" "T"
                      "GCG" "A"
                      "UAU" "Y"
                      "CAU" "H"
                      "AAU" "N"
                      "GAU" "D"
                      "UAC" "Y"
                      "CAC" "H"
                      "AAC" "N"
                      "GAC" "D"
                      "UAA" "" #_"Stop"
                      "CAA" "Q"
                      "AAA" "K"
                      "GAA" "E"
                      "UAG" "" #_"Stop"
                      "CAG" "Q"
                      "AAG" "K"
                      "GAG" "E"
                      "UGU" "C"
                      "CGU" "R"
                      "AGU" "S"
                      "GGU" "G"
                      "UGC" "C"
                      "CGC" "R"
                      "AGC" "S"
                      "GGC" "G"
                      "UGA" "" #_"Stop"
                      "CGA" "R"
                      "AGA" "R"
                      "GGA" "G"
                      "UGG" "W"
                      "CGG" "R"
                      "AGG" "R"
                      "GGG" "G"})

(->> "rosalind/prot"
     io/resource
     slurp
     (partition 3)
     (map #(apply str %))
     (map rna-codon-table)
     (apply str))

